### ISSUE TITLE
1.7.7.0 Uncaught TypeError: formZoneElem.magnificPopup is not a function

### ISSUE THREAD

**Issue by majastanislawska** [PrestaShop/PrestaShop#22258]
#### Describe the bug

Since upgrade to 1.7.7.0 various javascript stuff on back-end doesn't work leaving trace of `something is not a function` in browser console
Lack of product image upload being most annoying, hence subject.

Upgrade was from 1.7.5.2, failed on sql update, caught up manually. schema issue seems unrelated
files are unmodified from distribution, except for `classes/controller/AdminController.php` (see #22250)
which also seems unrelated.
 

#### Expected behavior
Upgrade should work flawlessly ;-)

#### Steps to Reproduce

ahem

**Screenshots**
there are few screenshots on #22231 that show same 

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.4.13 and 7.3.25 (unrelated)

**Comment by matks** [comment]
Hi, this look similar to issue https://github.com/PrestaShop/PrestaShop/issues/22255 which has a workaround, can you check and tell if it is the same issue (and if the workaround works) ?

**Comment by majastanislawska** [comment]
html source did not indicated jquery being loaded twice, but following hint l checked sources of all modules hooking to displayBackOfficeHeader.
culprit was shipping module InPostShip (thats parcelmodel style carrier in poland),
that had `$this->context->controller->addJS('/js/jquery/jquery-1.11.0.min.js');` commenting that out solves problem.
This was working fine prior to upgrade, 
Shouldn't controller check for duplicates in addJS? or is is a path issue?

**Comment by matks** [comment]
We upgraded jQuery version in BO from v1.1 to v3.4 (details https://devdocs.prestashop.com/1.7/modules/core-updates/1.7.7/).

This module does something quite bad which is it injects jQuery itself. PrestaShop is supposed to take care of that, there is a function especially for that `addJquery()`.

Maybe when the module was loading jQuery 1.1 AND PrestaShop was loading jQuery 1.1 there was no issue but now it's likely on the BO there is both jQuery 1.1 (because of the module) and jQuery 3.4 (PrestaShop loads it) which results in this situation.

**Comment by matks** [comment]
I close this issue as the problem comes from the module but I think we'll hear about other modules that do this mistake too 😅 . Well ... they now know what they need to do to ensure compatibility with PS 1.7.7

(and it's better we have jQuery 3.4 in BO rather than old EOL jQuery 1.1)

**Comment by majastanislawska** [comment]
Sure, Thanks.
There is way more things around here that approach EOL ;-)
Good luck.
