### ISSUE TITLE
Uncaught TypeError: this._addClass is not a function in Product add/edit page

### ISSUE THREAD

**Issue by yvgorshkov** [PrestaShop/PrestaShop#15741]
**Describe the bug**
After updating to 1.7.6.1, the page for adding and editing products stopped working.

**To Reproduce**
Just open the page for adding or editing products and the following error appears in the browser console:

```
main.bundle.js:221 Uncaught TypeError: this._addClass is not a function
    at e.<computed>.<computed>._create (main.bundle.js:221)
    at e.<computed>.<computed>._create (jquery.ui.widget.min.js:4)
    at e.<computed>.<computed>._createWidget (jquery.ui.widget.min.js:4)
    at new e.<computed>.<computed> (jquery.ui.widget.min.js:4)
    at HTMLDivElement.<anonymous> (jquery.ui.widget.min.js:4)
    at Function.each (main.bundle.js:253)
    at De.fn.init.each (main.bundle.js:253)
    at De.fn.init.e.fn.<computed> [as sortable] (jquery.ui.widget.min.js:4)
    at r.init (form.js?1.7.6.1:1385)
    at r.value (main.bundle.js:253)
```

Tip: If I comment line number 46 in classes/Media.php, where the slider connection is located:

```
'ui.slider' => array('fileName' => 'jquery.ui.slider.min.js', 'dependencies' => array('ui.core', 'ui.widget', 'ui.mouse'), 'theme' => true),
```

the form starts working fine. But many others cease to function.
The same effect is obtained if we separately exclude the ui.widget or ui.mouse on this line.

Tip2: Disabling all third-party modules in the settings does not help.

**Additional information**
PrestaShop version: 1.7.6.1
PHP version: 7.0.33-0ubuntu0.16.04.6

**Comment by khouloudbelguith** [comment]
Hi @yvgorshkov,

What is the exact version of the module 1-click upgrade did you use?
Have you any errors during the upgrade?
Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in `<admin folder>/autoupgrade/tmp/log.txt`
>Disabling all third-party modules in the settings does not help.

Did you disable the "Disable non PrestaShop modules" option in the BO => Advanced Parameters => Performance page?
Those options "Disable non PrestaShop modules " & "Disable all overrides" do not work as reported here:
https://github.com/PrestaShop/PrestaShop/issues/9965
https://github.com/PrestaShop/PrestaShop/issues/14596

Thanks!

**Comment by yvgorshkov** [comment]
Hi @khouloudbelguith 

> What is the exact version of the module 1-click upgrade did you use?

I use: 1-Click Upgrade v4.9.0 - by PrestaShop

> Have you any errors during the upgrade?

No, there were no errors

> Can you please provide us the log of your upgrade? It can be found in the log.txt file, available in <admin folder>/autoupgrade/tmp/log.txt

download log.txt here: [https://www.sendspace.com/file/a9i7g6](https://www.sendspace.com/file/a9i7g6)

> Those options "Disable non PrestaShop modules " & "Disable all overrides" do not work

I tried to completely remove modules that use AdminProduct hooks. Did not solve the problem.

**Comment by khouloudbelguith** [comment]
@yvgorshkov, thanks for your feedback.
Yes! your upgrade is OK.
Could you please provide us with more info? We need more details to understand how we can reproduce your issue:
 - server setup and configuration
 - debug mode report
 - PHP error logs
 - apache error log
 - screenshots

Don't you know how to get this information? Please read the following article:
http://build.prestashop.com/howtos/misc/how-to-create-bug-report/

Thanks!

**Comment by khouloudbelguith** [comment]
Hi @yvgorshkov,

Since we had no news from you for more than 30 days, I'll close this ticket. Feel free to open another one if you can give specific details.

Thanks!
