### ISSUE TITLE
Error during upgrade 1.7.4.3 -> 1.7.5.0 beta 1 build 2

### ISSUE THREAD

**Issue by marionf** [PrestaShop/PrestaShop#11142]
**Describe the bug**
Error during upgrade 1.7.4.3 -> 1.7.5.0 beta 1 build 2

**To Reproduce**
1. Go to Modules > Autoupgrade
2. Make the upgrade with the archive of 1.7.5.0 beta 1 build 2
3. See error

**Screenshots**

![capture d ecran_511](https://user-images.githubusercontent.com/13449658/47432190-dd73ef00-d79d-11e8-9ccc-388c63ff1f98.png)

![capture d ecran_512](https://user-images.githubusercontent.com/13449658/47432196-e369d000-d79d-11e8-964e-fbf71c62064a.png)

![capture d ecran_513](https://user-images.githubusercontent.com/13449658/47432204-e82e8400-d79d-11e8-900c-14eb78f821d4.png)

**Additionnal information**
PrestaShop version: N/A
PHP version: N/A

**Comment by eternoendless** [comment]
Wdyt @Quetzacoalt91 ? It looks like it's using an old file to invoke a new one

**Comment by Quetzacoalt91** [comment]
Yep, some class construction got their definition updated, and the symfony container is not aware of it because of the prod mode.

The cache needs to be cleared.

**Comment by MathiasReker** [comment]
Where can I download 1.7.5.0 beta 1 build 2?

**Comment by matks** [comment]
@MathiasReker It will be available very soon 😉 we're making sure the "obvious" bugs are fixed before making it public in order not to waste beta testers precious time

**Comment by marionf** [comment]
I just tried an upgrade from 1.7.4.4 to 1.7.5.0 beta 1 build 4 and I don't have this issue

**Comment by khouloudbelguith** [comment]
Hi,

Error during upgrade 1.7.4.3 -> 1.7.5.0 beta 1 build 4.
`
[INTERNAL] /projet/prestashop/prestashop/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php line 348 - Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "prestashop.bundle.routing.converter.legacy_url_converter". #0 /projet/prestashop/prestashop/classes/Link.php(723): Symfony\Component\DependencyInjection\Container->get('prestashop.bund...') #1 /projet/prestashop/prestashop/modules/ps_themecusto/ps_themecusto.php(61): LinkCore->getAdminLink('AdminPsThemeCus...') #2 [internal function]: ps_themecusto->__construct() #3 /projet/prestashop/prestashop/src/Core/Foundation/IoC/Container.php(130): ReflectionClass->newInstance() #4 /projet/prestashop/prestashop/src/Core/Foundation/IoC/Container.php(163): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->makeInstanceFromClassName('ps_themecusto', Array) #5 /projet/prestashop/prestashop/src/Core/Foundation/IoC/Container.php(176): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->doMake('ps_themecusto', Array) #6 /projet/prestashop/prestashop/src/Adapter/ServiceLocator.php(65): PrestaShop\PrestaShop\Core\Foundation\IoC\Container->make('ps_themecusto') #7 /projet/prestashop/prestashop/classes/module/Module.php(1137): PrestaShop\PrestaShop\Adapter\ServiceLocator::get('ps_themecusto') #8 /projet/prestashop/prestashop/classes/module/Module.php(1116): ModuleCore::coreLoadModule('ps_themecusto') #9 /projet/prestashop/prestashop/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(193): ModuleCore::getInstanceByName('ps_themecusto') #10 /projet/prestashop/prestashop/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(32577, 'ps_themecusto') #11 /projet/prestashop/prestashop/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run() #12 {main}
ROLLBACK
`

Thanks!

**Comment by jolelievre** [comment]
I tried a bunch of times but only could reproduce it once.. couldn't reproduce it another time nor try to fix it

**Comment by marionf** [comment]
Hi everyone,
Do you think we should close this one as can't reproduce ?

**Comment by Quetzacoalt91** [comment]
I'll make another try on Windows, and I'd like to see more people trying with their own environment. If we definitely cannot reproduce before the release of 1.7.5.0, we will close this issue.

**Comment by Quetzacoalt91** [comment]
Upgrade 1.7.4.3 >> 1.7.5.0 went fine on Windows (IIS / PHP FastCGI), but no modules were upgraded during the process. :/

**Comment by Quetzacoalt91** [comment]
Closing until further feedback.

**Comment by marionf** [comment]
I have this issue when I try an upgrade from 1.7.4.4 to 1.7.5.0 RC1 build 1 with autoupgrade module v4.5.0

`
[INTERNAL] /var/www/html/prestashop_1.7.4.4/src/PrestaShopBundle/Service/DataProvider/Marketplace/ApiClient.php line 44 - Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function PrestaShopBundle\Service\DataProvider\Marketplace\ApiClient::__construct(), 5 passed in /var/www/html/prestashop_1.7.4.4/var/cache/prod/ContainerQ4kwxyg/getPrestashop_Addons_ClientApiService.php on line 8 and exactly 6 expected #0 /var/www/html/prestashop_1.7.4.4/var/cache/prod/ContainerQ4kwxyg/getPrestashop_Addons_ClientApiService.php(8): PrestaShopBundle\Service\DataProvider\Marketplace\ApiClient->__construct(Object(GuzzleHttp\Client), 'fr-FR', 'FR', Object(PrestaShop\PrestaShop\Adapter\Tools), 'http://localhos...') #1 /var/www/html/prestashop_1.7.4.4/var/cache/prod/ContainerQ4kwxyg/appProdProjectContainer.php(882): require('/var/www/html/p...') #2 /var/www/html/prestashop_1.7.4.4/var/cache/prod/ContainerQ4kwxyg/getPrestashop_Core_Admin_DataProvider_AddonsInterfaceService.php(8): ContainerQ4kwxyg\appProdProjectContainer->load('getPrestashop_A...') #3 /var/www/html/prestashop_1.7.4.4/var/cache/prod/ContainerQ4kwxyg/appProdProjectContainer.php(882): require('/var/www/html/p...') #4 /var/www/html/prestashop_1.7.4.4/var/cache/prod/ContainerQ4kwxyg/getPrestashop_Core_Module_UpdaterService.php(8): ContainerQ4kwxyg\appProdProjectContainer->load('getPrestashop_C...') #5 /var/www/html/prestashop_1.7.4.4/var/cache/prod/ContainerQ4kwxyg/appProdProjectContainer.php(882): require('/var/www/html/p...') #6 /var/www/html/prestashop_1.7.4.4/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(304): ContainerQ4kwxyg\appProdProjectContainer->load('getPrestashop_C...') #7 /var/www/html/prestashop_1.7.4.4/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(76): Symfony\Component\DependencyInjection\Container->get('prestashop.core...') #8 /var/www/html/prestashop_1.7.4.4/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(190): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->getModuleDataUpdater() #9 /var/www/html/prestashop_1.7.4.4/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(22312, 'blockreassuranc...') #10 /var/www/html/prestashop_1.7.4.4/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run() #11 {main}
`

**Comment by mickaelandrieu** [comment]
Hi @marionf,

are you able to reproduce it?

**Comment by khouloudbelguith** [comment]
I have the same issue after upgrade from 1.7.4.4 => 1.7.50RC1 with the 1-click upgrade 4.5.0.

`[INTERNAL] /var/www/html/upgrade/1744/src/PrestaShopBundle/Service/DataProvider/Marketplace/ApiClient.php line 44 - Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Too few arguments to function PrestaShopBundle\Service\DataProvider\Marketplace\ApiClient::__construct(), 5 passed in /var/www/html/upgrade/1744/var/cache/prod/ContainerHsf9ftf/getPrestashop_Addons_ClientApiService.php on line 8 and exactly 6 expected #0 /var/www/html/upgrade/1744/var/cache/prod/ContainerHsf9ftf/getPrestashop_Addons_ClientApiService.php(8): PrestaShopBundle\Service\DataProvider\Marketplace\ApiClient->__construct(Object(GuzzleHttp\Client), 'en-US', 'FR', Object(PrestaShop\PrestaShop\Adapter\Tools), 'http://127.0.0....') #1 /var/www/html/upgrade/1744/var/cache/prod/ContainerHsf9ftf/appProdProjectContainer.php(882): require('/var/www/html/u...') #2 /var/www/html/upgrade/1744/var/cache/prod/ContainerHsf9ftf/getPrestashop_Core_Admin_DataProvider_AddonsInterfaceService.php(8): ContainerHsf9ftf\appProdProjectContainer->load('getPrestashop_A...') #3 /var/www/html/upgrade/1744/var/cache/prod/ContainerHsf9ftf/appProdProjectContainer.php(882): require('/var/www/html/u...') #4 /var/www/html/upgrade/1744/var/cache/prod/ContainerHsf9ftf/getPrestashop_Core_Module_UpdaterService.php(8): ContainerHsf9ftf\appProdProjectContainer->load('getPrestashop_C...') #5 /var/www/html/upgrade/1744/var/cache/prod/ContainerHsf9ftf/appProdProjectContainer.php(882): require('/var/www/html/u...') #6 /var/www/html/upgrade/1744/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(304): ContainerHsf9ftf\appProdProjectContainer->load('getPrestashop_C...') #7 /var/www/html/upgrade/1744/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(76): Symfony\Component\DependencyInjection\Container->get('prestashop.core...') #8 /var/www/html/upgrade/1744/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(190): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->getModuleDataUpdater() #9 /var/www/html/upgrade/1744/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(22312, 'blockreassuranc...') #10 /var/www/html/upgrade/1744/admin-dev/autoupgrade/ajax-upgradetab.php(52): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run() #11 {main}`

Thanks!

**Comment by Quetzacoalt91** [comment]
Nice, this time we have several person who will be able to try the future fix. :)

**Comment by Quetzacoalt91** [comment]
Can you please try with https://github.com/PrestaShop/autoupgrade/pull/195?

**Comment by marionf** [comment]
No more error for me :+1:

**Comment by colinegin** [comment]
#11678
