### ISSUE TITLE
After upgrade to 1.7.7.0 from 1.7.6.4 a lot of js libraries in admin panel do not load

### ISSUE THREAD

**Issue by ProteanCode** [PrestaShop/PrestaShop#22343]
#### Describe the bug

Getting this when editing product

```
form.js?1.7.7.0:1440 Uncaught TypeError: formZoneElem.magnificPopup is not a function
    at form.js?1.7.7.0:1440
    at form.js?1.7.7.0:1536
(anonymous) @ form.js?1.7.7.0:1440
(anonymous) @ form.js?1.7.7.0:1536
90?_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXs:4517 Uncaught TypeError: $(...).modal is not a function
    at HTMLDocument.<anonymous>
```

#### Additional information

* PrestaShop version: 1.7.7.0
* PHP version: 7.2

**Comment by ProteanCode** [comment]
I replaces the whole themes directory from fresh download from the site

**Comment by matks** [comment]
We had 2 similar bug reports
- https://github.com/PrestaShop/PrestaShop/issues/22255
- https://github.com/PrestaShop/PrestaShop/issues/22258

We found that each time it was a 3rd party module that introduced the issue. We upgraded jQuery to version 3 in PrestaShop 1.7.7.0 and some modules do not support this (or load jQuery 1 which creates conflicts).

**Comment by ProteanCode** [comment]
> We had 2 similar bug reports
> 
> * #22255
> * #22258
> 
> We found that each time it was a 3rd party module that introduced the issue. We upgraded jQuery to version 3 in PrestaShop 1.7.7.0 and some modules do not support this (or load jQuery 1 which creates conflicts).

Thanks. Do you know what OOD module is? I cannot find it. I will turn off and on some modules now

**Comment by hibatallahAouadni** [comment]
Hello @ProteanCode 

Your issue is not related to PrestaShop Core, so I'm closing this issue but you can keep discuss the cause of your problem with @matks here.

If you have questions about using PrestaShop or third-party modules, or if you need help with your shop, please consider one
of our [support plans](https://www.prestashop.com/support).

Alternatively, you can also ask for help in the [community forums](https://www.prestashop.com/forums/) or in the [public Slack channel](https://github.com/PrestaShop/open-source/tree/master/slack).

Thank you

**Comment by ProteanCode** [comment]
Okay so I had a problem that something loaded a jquery 1.11 in admin panel from /js/jquery/jquery-1.11.min.js

I was greping the whole project for files that contain it and did a lot just to give up and rename the file to something meaningless

The UI changed a little after that but seems to be working... the (*!&@

**Comment by ProteanCode** [comment]
Can we get rid of that jquery-1.11 from the js folder? It's also getting loaded somewhere in AdminController

**Comment by SimonGrn** [comment]
Hello @ProteanCode,
It's from one of your installed modules. You can try disabling them one at a time to see which one is causing your issue.

**Comment by ProteanCode** [comment]
> Hello @ProteanCode,
> It's from one of your installed modules. You can try disabling them one at a time to see which one is causing your issue.

It's actually not. The PHP Media.php class is a core object and it does have getJqueryPath method (returns 1.11) that is used by other modules, but this is not modules fault. This is a breaking change that should be adressed since it can break like half of existing PS instances.

If prestashop allows to include a jq1, then they say "oh its external module fault, turn it off" and until that **the whole damn admin panel stops to work**, for some people making them unable to log in because PS is heavly dependent on JQ.

What should be done is to create a way to detect conflicting plugins and put them inactive as a part of the upgrade step. The getJqueryPath has deprecation mark so they know its a thing.

A plugin that has not been tested to work with newest version should be disabled by default, including plugins outside of prestashop marketplace. You cannot disable plugins if you can't log in into admin panel... so no, its not a "module" fault, but incorrect core handling of such modules.

I know I am ranting now, but I feel I have a reason for

**Comment by SimonGrn** [comment]
> It's actually not. The PHP Media.php class is a core object and it does have getJqueryPath method (returns 1.11) that is used by other modules, but this is not modules fault. This is a breaking change that should be adressed since it can break like half of existing PS instances.

This is concerning, I'm asking the developers to make sure this is a real problem in the Core.

> If prestashop allows to include a jq1, then they say "oh its external module fault, turn it off" and until that **the whole damn admin panel stops to work**, for some people making them unable to log in because PS is heavly dependent on JQ.

I'm following the issues created and I can't remember seeing this before (I might have missed it), that's why I used this answer which worked previously 100% of the time, as @matks said.

> What should be done is to create a way to detect conflicting plugins and put them inactive as a part of the upgrade step. The getJqueryPath has deprecation mark so they know its a thing.

Yes, this is a good idea. If you feel like helping the project, feel free to make a Pull Request to improve it ! This is a lot of work though, and as you may suspect we already have a lot of priority 1 subjects.

> A plugin that has not been tested to work with newest version should be disabled by default, including plugins outside of prestashop marketplace. You cannot disable plugins if you can't log in into admin panel... so no, its not a "module" fault, but incorrect core handling of such modules.

We cannot test every configuration and every module with every combination of modules/PS version/PHP version, as we have limited ressources for that. What we can't do could be done by the community, tho 😉 

> I know I am ranting now, but I feel I have a reason for

You have, but I'm gonna be a little blunt: this is an Open Source Project, you're welcome to contribute to improve it. When people write issues, that's really appreciable, **BUT** the burden of investigating, reproducing, fixing, maintaining this fix, is on us; when the benefice of the fix is for the whole community. For free.
That's why we welcome your contribution (don't get me wrong !) but maintaining this whole project is a heck of a lot of work and our ressources are limited, we have to prioritize and select what we're working on.

I hope you understand, even if we're drifting away a little from the subject here.

**Comment by ProteanCode** [comment]
I do understand what and how open source works with all its pros and cons, but I really would wish that a stable release would be more stable while in fact the most stable release seems to be master/develop branch where all fixes goes in the fastest possible way.

Prestashop is semi-opensource because of the official marketplace with addons that cuts at least 30% of profits (w/o taxes) from sells. Semi-opensource because most of opensource projects usually do not have a hegemonic centralized Point of Sale, and because of that other developers makes own plugins outside of that place. Prestashop is opensource project **driven by bugs** ever since like 2014 ( the code in #20921 has never changed).

A top world ecommerce shop with centralized point of sale definitely can at least create some loyalty programs to encourage people for doing stuff right and regularly. Allow to bind github account with prestashop account and reduce the 30% penalty from selling if the developer actually help with the core. They can do that, they can give a real money to devs who are actually good on making prestashop stuff.

Instead what we get is a "stable" release with that on the end:

> PrestaShop is above all a community project: from the 119 committers who contributed to this release, the vast majority are not directly affiliated with the PrestaShop company. Also, **57 people contributed for their first time to PrestaShop in this version!**

With all respect to people who spent their time on this project - you are spending your time for free on a company that have insane budget in the name of "stable" releases made by half of people that possibly had no clue what they were doing. This is a miracle that in so fast paced world like today we still have people with free time to spend on such things.

This is wrong.

Went off the track totally at this point. I think its time to close that issue.
_Edit: Ah its already closed_

**Comment by SimonGrn** [comment]
> I do understand what and how open source works with all its pros and cons, but I really would wish that a stable release would be more stable while in fact the most stable release seems to be master/develop branch where all fixes goes in the fastest possible way.

A stable release is as stable as it can be, given the ressources attached to it. We have 4 testers, who spent the last TWO MONTHS breaking every release candidate. This is huge, given the size of the company and the size of the dev team (10 developers). 
Adopting a faster release cycle would not be the best idea as a lot of people (and I mean a lot) don't upgrade, w/e the context. We have already a lot of fragmentation, with obligation of backward compatibility.

> Prestashop is semi-opensource because of the official marketplace with addons that cuts at least 30% of profits (w/o taxes) from sells. Semi-opensource because most of opensource projects usually do not have a hegemonic centralized Point of Sale, and because of that other developers makes own plugins outside of that place. Prestashop is opensource project **driven by bugs** ever since like 2014 ( the code in #20921 has never changed).

The official marketplace is decouplable from the core (a lot of developers are selling their themes and modules outside of PrestaShop and that works very well). This repository is about the core and only the core, Addons pay for some of the developers that work on the project (we have external maintainers, it's not just the company that drive the project !!!), the marketing, the product team, etc... 

Today, PrestaShop employees (paid by the money made from Addons) make 80% of the contributions, but represent 20% of the contributors. This means that a lot of merchants/agencies/developers actually get a full product, for free, make money with it but never contribute. How can that work on the long term ?

> A top world ecommerce shop with centralized point of sale definitely can at least create some loyalty programs to encourage people for doing stuff right and regularly. Allow to bind github account with prestashop account and reduce the 30% penalty from selling if the developer actually help with the core. They can do that, they can give a real money to devs who are actually good on making prestashop stuff.

There are some paths actually explored to get people more involved, but money is not a good choice. Making agencies/developers understand that it's for their own benefit to fix a bug, that fixing one bug and giving the fix for free to the community is hugely beneficial (if 10 agencies fix a bug, every agency get 10 fix for the price of one), this will be a better way.

> With all respect to people who spent their time on this project - you are spending your time for free on a company that have insane budget in the name of "stable" releases made by half of people that possibly had no clue what they were doing. This is a miracle that in so fast paced world like today we still have people with free time to spend on such things.

Insane budget ? How did you get that ? Did you compare with Automattic, Magento or Shopify ? The maintainers team is 10 developers, and that's 80% of the contributions !

Anyway you're right, the conversation is drifing away and sadly your tone is becoming more agressive. I'm locking this topic, I hope we'll be able to understand each other's point of view one day.

Thank you for your understanding.

**Comment by ttoine** [comment]
Hello, you are not respecting the Code of Conduct of the project. Plus, you are off topic and agressive with your last comment. That's why this issues has been closed, I hope that you guessed it.

The PrestaShop software is indeed a true open source project (there is no proprietary derivative and no restriction to use) and the PrestaShop Company is indeed the most important contributor to this project. But developing, sustaining and promoting an open source project costs a lot, that's why we also have a business model (the marketplace is part of it, but not only).

That said, your contributions are very welcome. But if you want people to spend time to review them, you should change your communication. Nobody, paid or not, want to work with someone agressive and not respectful. So, now, if this issue is really important and you still want to work on it, maybe it's time to edit your posts, change the content. Being friendly is always better to get things done.
