### ISSUE TITLE
JS errors on product edit page

### ISSUE THREAD

**Issue by go-sudo** [PrestaShop/PrestaShop#22534]
Hello

After upgrade to 1.7.7.0  js libraries in ...

form.js?1.7.7.0:1440 Uncaught TypeError: formZoneElem.magnificPopup is not a function
    at form.js?1.7.7.0:1440
    at form.js?1.7.7.0:1536
jquery-3.4.1.min.js:2 Uncaught TypeError: $(...).modal is not a function
    at HTMLDocument.<anonymous> (132?_token=9oXbZS2VuUZPYyTZFm5kielOQydj2Q0IjSQ5crcZElA:4857)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
jquery-3.4.1.min.js:2 Uncaught TypeError: $(...).tooltip is not a function
    at HTMLDocument.<anonymous> (default.js?1.7.7.0:7)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
jquery-3.4.1.min.js:2 Uncaught TypeError: n(...).popover is not a function
    at HTMLDocument.<anonymous> (form_popover_error.bundle.js?1.7.7.0:25)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)
jquery-3.4.1.min.js:2 Uncaught TypeError: $(...).tokenfield is not a function
    at HTMLDivElement.<anonymous> (form.js?1.7.7.0:902)
    at HTMLDivElement.r.complete (jquery-3.4.1.min.js:2)
    at c (jquery-3.4.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.4.1.min.js:2)
    at u (jquery-3.4.1.min.js:2)
    at Function.k.fx.tick (jquery-3.4.1.min.js:2)
    at lt (jquery-3.4.1.min.js:2)
    at Function.k.fx.start (jquery-3.4.1.min.js:2)
    at Function.k.fx.timer (jquery-3.4.1.min.js:2)
    at dt (jquery-3.4.1.min.js:2)
jquery-3.4.1.min.js:2 Uncaught Error: No Dropzone found for given element. This is probably because you're trying to access it before Dropzone had the time to initialize. Use the `init` option to setup any additional observers on your Dropzone.
    at Function.u.forElement (main.bundle.js:277)
    at HTMLDocument.<anonymous> (product_page.bundle.js?1.7.7.0:12)
    at e (jquery-3.4.1.min.js:2)
    at t (jquery-3.4.1.min.js:2)

**Comment by matks** [comment]
Hi @go-sudo this is something that has been reported before, see https://github.com/PrestaShop/PrestaShop/issues/22258

We found that each time someone reported this bug ; it was a 3rd party module that introduced the issue. We upgraded jQuery to version 3 in PrestaShop 1.7.7.0 and some modules do not support this (or load jQuery 1 which creates conflicts).

**Comment by SimonGrn** [comment]
Hello,
Thanks for your issue. **You must follow the template to submit a complete bug report**. 
Read more about how we expect the issues to be handled [here](https://build.prestashop.com/news/how-bug-reports-are-handled/). Feel free to create a new issue if you are able to follow a simple template, we will be glad to investigate it. 

Thank you

**Comment by go-sudo** [comment]
@matks how to restore prestashop to older version please, not all modules are upgraded yet to use jQuery version 3

**Comment by go-sudo** [comment]
@SimonGrn le bug est claire est connu en plus j'ai bien mentionné la version de PS et la page ou le souci persiste dans le titre.
aucun des développeurs a pu résoudre le souci du coup je reste sur la version 1.7.6.5 , le temps qu'ils mettent leur module à jour

**Comment by SimonGrn** [comment]
@go-sudo 
You need to use the backup you made before upgrading, like the autoupgrade module highly suggested you. You should always make a full backup before upgrading.

Regarding your second comment:
* please use English here
* is this is a known problem, why would you create another issue ? We already know the problem, as @matks pointed you.
* you need to follow the template. this is not a complicated thing, we are humans, we have limited time, we cannot waste our precious time arguing and trying to understand what went wrong in poorly described issues (you just pasted a log, seriously ?). Please have some respect for us, we only ask you ONE thing: following the template. Like everybody else does.

**If you don't respect us, how do you expect us to react, exactly ?**

Thank you for your understanding.
