### PR TITLE
Fix synchronous loaded scripts

### PR DESCRIPTION
**Pull request by Shudrum**
| Questions | Answers |
| --- | --- |
| Branch? | 1.6.1.x |
| Description? | Synchronous calls are deprecated, this PR is about remove all of them. |
| Type? | bug fix |
| Category? | BO |
| BC breaks? | ??? |
| Deprecations? | ??? |
| Fixed ticket? | http://forge.prestashop.com/browse/PSCSX-8524 |

### CODE REVIEW

**Comment by hadjedjvincent** [comment]
Planned for 1.6.1.9, really ?

**Comment by Shudrum** [comment]
Our 1.6.1.8 process is running …

But it does not mean it one month. It will be available as soon as the fix is correctly tested. Also, we will provide more informations for people who don't want to upgrade their shops and apply the fix manually.

**Comment by Shudrum** [comment]
And if the fix is ok before the 1.6.1.8, we will integrate the fix into, of course.

**Comment by Shudrum** [comment]
Last update thanks to @firstred!

Many many many thanks for the time and effort!

**Comment by themella** [comment]
I made fix in two different 1.6.1.6 prestashop and in one of them bug is fixed in the second one now you are not able to save modification or new products cause you press "save" and "save and stay" button but nothing will happend.

**Comment by AntoInta** [comment]
Hello everybody,
before applying this fix I realized that in Google Chrome v. 53.x.x.x the problem raised by @themella (nothing happens after clicking on "Save" or "Save and Stay")
is not present, but after the update to Chrome v. 54.x.x.x it comes out!

Hope this could be useful.

Thanks to everybody for your efforts

**Comment by firstred** [comment]
No, that's not correct. It will still send only half of the form in some cases. The reason why not removing the stuff in `form.tpl` works for you is because the `e.preventDefault();` is still in the PR (this prevents the form from submitting). That is the one that should be removed.

**Comment by Ledfanatic** [comment]
Ok, I understand. Thank you for the tip.

**Comment by dave-lp** [comment]
this seems to have fixed 1.6.1.5, customer signed off, will check more as i get support tickets on them.

**Comment by dave-lp** [comment]
1.6.1.6 fixed with these edits.  Customer's problem went away.

**Comment by Ledfanatic** [comment]
On prestashop 1.6.1.4 when you add a picture you still have the "jquery-1.11.0.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated ".
Thanks

**Comment by themella** [comment]
I made a lot of test and I can confirm : FIX DON'T WORK for 1.6.1.6 and 1.6.1.5  cause when you change all 9 files button doesn't work at all. 

So solution isn't applicable and all my customer still have chrome problem.  

there is any news about fixing this really bad bug? actually bug isn't fixed.

**Comment by Ledfanatic** [comment]
I am on 1.6.1.4 and the button works fine with latest Google Chrome release. I only have sometimes the "jquery-1.11.0.min.js:4 Synchronous XMLHttpRequest on the main thread is deprecated " and immediately after lot of errors JS and dnd then a deconnection from my back office.

**Comment by themella** [comment]
@Ledfanatic 

with pc or mac Platform? 

I found with pc platform buttond die with mac button survive and work fine.

**Comment by Ledfanatic** [comment]
I am on PC platform. Windows 8.1. Chrome 54.0.2840.71 m (64-bit)

**Comment by themella** [comment]
I found problem with windows 10 anche chrome 54.0.2840.87 m (64bit) lastest one.

**Comment by Ledfanatic** [comment]
I just upgraded to Chrome 54.0.2840.87 m (64bit) and button works fine too...

**Comment by themella** [comment]
@Ledfanatic 
@Shudrum 

I can't understand why in some pc works and other not work.

**Comment by katenagel** [comment]
I am using 1.6.1.4 and my file is different than the one shown. How do I find the correct line?

**Comment by Ledfanatic** [comment]
@themella 
@Shudrum 

After more tests I encountered a problem. the Save and stay button works (modification saved) but the save button didn't save any more !!

**Comment by themella** [comment]
After million of test i found the key.
Chrome don't update correcly js file.

You need to open in new panel trought developer source panel any js file to be sure are updated. 

after that fix seems work correctly. Tested on 1.6.1.5 tomorrow i will test on other version.

**Comment by carvisionuk** [comment]
This is a very strange one to be fair!! 
i've updated all files, and mods, and now can save in Google Chrome (54) and also Firefox (never experienced an issue here anyways) Microsoft Edge, 

As before i had no way to save or change product descriptions, until i did the mods, now i can make between two or three changes, before it stops updating again, Both Chrome and Edge, but Firefox still updates regardless, 

i'm running 1.6.1.8 

Can i try anything else? been trying to fix this for sometime now and slowly loosing the will to live!! lol.

**Comment by dave-lp** [comment]
Did you clear your web browser cache?  Did you set smarty to recompile if
changes?  You have to do both

**Comment by carvisionuk** [comment]
Hi David,
Thank you for your reply,
Yes I cleared the Web Browser on my PC and also cleared Smarty in BO

**Comment by carvisionuk** [comment]
Do you know if all modified files are in 1.6.1.9?

**Comment by Ledfanatic** [comment]
@dave-IP

Web browser cleared and "smarty recompile if changes" OK. 
After some days it seems better for the moment no more Synchronous deprecated when save or stay and save.

I still get the synchronous message deprecated when I upload new pictures for a product, just after I click on the "upload files" button ? catalog>products>images>add files>upload files

Any of you with the same error ? Thank you.

**Comment by gskema** [comment]
I can confirm that this isn't working on `Version 55.0.2883.28 beta (64-bit)` either.

**Comment by gskema** [comment]
@Shudrum Does this replace **all** of the *sync* calls? My search found a total of 37 `async: false` code occurrences.

**Comment by Shudrum** [comment]
@gskema Yep, we fix the product page first.

**Comment by cdbruin** [comment]
I tested it on 1.6.1.3 and unfortunately now my buttons are spinning with the following error:
 Uncaught TypeError: $(...).typeahead is not a function(…)

**Comment by firstred** [comment]
Does it help if you wrap it in a `$(document).ready()` ?

**Comment by cdbruin** [comment]
No unfortunately it does not help.

**Comment by xBorderie** [comment]
We have released 1.6.1.9 with this fix: http://build.prestashop.com/news/prestashop-1619-maintenance-release/
Thank you for your help testing it, everyone!

**Comment by cdbruin** [comment]
I use version 1.6.3 on my production server and can't just upgrade.
Somehow this fix does not work on my multistore server.
I have reverted back to chrome 53 and that seems to fix it also.
Somehow the typeahead script is not run or not run in time.
keep getting the Uncaught TypeError: $(...).typeahead is not a function(…)

**Comment by Mimiwool** [comment]
Bonjour,

Pouvez-vous m'expliquer comment puis je installer le patch ci dessous fournit par prestashop ?
 https://github.com/PrestaShop/PrestaShop/pull/6749/files#diff-5336fdb784fed5a634ff94fd946cf644

C'est pour régler le soucis de l'enregistrement des produits qui mouline sans arrêt.
Merci d'avance

**Comment by Ledfanatic** [comment]
Bonjour,

Il faut modifier chacun des fichiers de votre installation prestashop indiqués dans le lien. Soit 9 fichiers a éditer, modifier et uploader par FTP dans les chemins indiqués..
Conseil, sauvegardez les versions originales avant d'envoyer les versions modifiées, une erreur est si vite arrivée.

**Comment by tomgug** [comment]
Unfortunately on my ps not works....

**Comment by firstred** [comment]
> Unfortunately on my ps not works....

Do you have some more info, with which we can figure out why it doesn't work on your instance of PrestaShop?

**Comment by tomgug** [comment]
I modified all files, deleted cache on ps, deleted cache on browser but when I open a product load infinitely.
I've same error described on this topic:
https://www.prestashop.com/forums/topic/451384-unresponsive-script-at-backoffice-product/ 

thanks

**Comment by firstred** [comment]
Have you checked if you applied the modifications correctly?

Some of the modifications set a timeout and reset it when the needed libraries (tinymce, typeahead) aren't there. This should stop once the libraries are loaded.

Do you see any errors when you open up Chrome's Developer Tools?

**Comment by tomgug** [comment]
this is the problem:
schermata 2016-11-11 alle 00 35 44

**Comment by firstred** [comment]
What else have you modified? There is no `jQuery` in `admin.js`: https://raw.githubusercontent.com/Shudrum/PrestaShop/73fd8dbed9f413a70f7d04fc4badd48f00ca501a/js/admin.js

**Comment by RempadDesign** [comment]
Hi, we have a problem after applying the patch to prestashop 1.6.1.0. All working good, but the subcategoryes are not loaded when try to add new product in the store: https://snag.gy/co2hwf.jpg

If we save the product and the page gets reloaded the subcategoryes will show, but it's anoying. I think this is a problem of ajax that is not loading dynamicaly the subcategoryes anymore...and they will show only after page refresh.

Thank you.

**Comment by serdib** [comment]
I have changed all 9 files, but it doesnt fix anything on Prestashop 1.6.1.2 (with Chrome_54.0.2840.99 on Windows_8)
Now when i open any product in BO i have many errors. See screen — [http://imgur.com/yRIaQZK](url)
And save buttons are spinning forever now.
What should i do? I cant just upgrade the whole shop to 1.6.1.9 because i have too many modified files.

P.S. in Internet Explorer 10 everithing works fine but it worked before this fix too.

**Comment by jorgevrgs** [comment]
Update tracking number is unavailable.

**Comment by Uebix** [comment]
A fix to this PR: https://github.com/PrestaShop/PrestaShop/pull/7179

**Comment by Cafesolo70** [comment]
Hi everybody, salut à tous 

Tentative de patch d'une 1.6.1.1,
là j'obtiens les boutons "Enregistrer" qui tourne  en attente indéfiniment 
et la console d'erreurs m'affiche ça : 
image
Merci pour votre aide

Attempt to patch a 1.6.1.1,
there I get the "Save" buttons that are spinning indefinitely
and the error console shows me that:
! [Image] (https://user-images.githubusercontent.com/21217308/58319407-22d2ca80-7e1a-11e9-9be3-a505b1393a02.png)
Thanks for your help
