### PR TITLE
Fix product page event theme sided not getting fired

### LINKED ISSUE #20044: JS crash on FO product page in 1.7.6.6, preventing updateProduct event to be received
#### Describe the bug

When changing an attribute e.g. Size or Color there is a JS error
TypeError: setTimeout(...).bind is not a functioncore.js:233:3320
    l http://localhost/presta176/themes/core.js:233
    <anonym> http://localhost/presta176/themes/core.js:233
    u http://localhost/presta176/themes/core.js:39
    add http://localhost/presta176/themes/core.js:39
    <anonym> http://localhost/presta176/themes/core.js:233
    emit http://localhost/presta176/themes/classic/assets/js/theme.js:1
    <anonym> http://localhost/presta176/themes/core.js:233
    dispatch http://localhost/presta176/themes/core.js:39
    handle http://localhost/presta176/themes/core.js:39
    receiveMessage resource://gre/actors/SelectChild.jsm:262
    receiveMessage resource://gre/actors/SelectChild.jsm:459

Due to this error it seems that updateProduct event is not triggered. You can test it with following code in the console:
	prestashop.on("updateProduct", (args) => {
            alert("test")
	});
It was working fine in 1.7.6.5 and 1.7.7.beta

#### Expected behavior

No error and updateProduct event triggered

#### Steps to Reproduce

Open an article with variants and choose any attribute - check JS console

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
grafik

#### Additional information

* PrestaShop version: 1.7.6.6
* PHP version: 7.2

### LINKED ISSUE #20048: Following bug #20047 it seems event updateProduct is not fired in 1.7.6.6 on Product FO Page
#### Describe the bug

Following bug #20047 it seems event updateProduct is not fired in 1.7.6.6 on Product FO Page. If confirmed, this will break any module listening to this JS event.

### PR DESCRIPTION
**Pull request by NeOMakinG**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Branch?       | 1.7.6.x
| Description?  | Using lint on a FO file wasn't a good idea, it completely broke event listeners after JS crash on product page, it means that events listeners inside theme couldnt work
| Type?         | bug fix
| Category?     | FO
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #20044 and https://github.com/PrestaShop/PrestaShop/issues/20048
| How to test?  | if you copy paste the code above inside your console after loading the product page, then change combinations/colors of a product, an alert should happen

 ```
prestashop.on("updateProduct", (args) => {
alert("test")
});
```

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/20052)

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you @NeOMakinG

**Comment by alerch** [comment]
Testet after update from 1.7.6.6 to 1.7.6.7 -> Error still persists.

**Comment by matks** [comment]
@alerch it might be some cache on your side 🤔  because we're 100% this issue is fixed in 1.7.6.7

Or maybe you have something else (custom theme, 3rd party module) that creates the same buggy behavior but the root issue is different
