### ISSUE TITLE
JS crash on FO product page in 1.7.6.6, preventing updateProduct event to be received

### ISSUE THREAD

**Issue by JBWModules** [PrestaShop/PrestaShop#20044]
#### Describe the bug

When changing an attribute e.g. Size or Color there is a JS error
TypeError: setTimeout(...).bind is not a functioncore.js:233:3320
    l http://localhost/presta176/themes/core.js:233
    <anonym> http://localhost/presta176/themes/core.js:233
    u http://localhost/presta176/themes/core.js:39
    add http://localhost/presta176/themes/core.js:39
    <anonym> http://localhost/presta176/themes/core.js:233
    emit http://localhost/presta176/themes/classic/assets/js/theme.js:1
    <anonym> http://localhost/presta176/themes/core.js:233
    dispatch http://localhost/presta176/themes/core.js:39
    handle http://localhost/presta176/themes/core.js:39
    receiveMessage resource://gre/actors/SelectChild.jsm:262
    receiveMessage resource://gre/actors/SelectChild.jsm:459

Due to this error it seems that updateProduct event is not triggered. You can test it with following code in the console:
	prestashop.on("updateProduct", (args) => {
            alert("test")
	});
It was working fine in 1.7.6.5 and 1.7.7.beta

#### Expected behavior

No error and updateProduct event triggered

#### Steps to Reproduce

Open an article with variants and choose any attribute - check JS console

**Screenshots**

If applicable, add screenshots or screen recordings to help explain your problem.
![grafik](https://user-images.githubusercontent.com/47666330/86446518-59189400-bd14-11ea-9151-5e70f6b7a67f.png)

#### Additional information

* PrestaShop version: 1.7.6.6
* PHP version: 7.2

**Comment by matks** [comment]
@JBWModules Hi ! We are investigating this issue, thanks for the very fast feedback !

**Comment by NeOMakinG** [comment]
Reproduced it, we're speaking about it right now

**Comment by matks** [comment]
We have different people trying to reproduce this and we have multiple outputs 😅 

Still under investigation

**Comment by matks** [comment]
@JBWModules Could you tell us
- if this is Classic Theme original or slightly modified ?
- if you have installed modules on product page ?
- your browser version

**Comment by matks** [comment]
@JBWModules Also did you notice this after 1.7.6.x => 1.7.6.6 upgrade or on fresh install of 1.7.6.6 ?

**Comment by JBWModules** [comment]
It's classic theme in an upgraded installation. To reproduce it is crucial to clear presta and browser cache to really work with new core.js.
I have my own developed modules installed but they only insert JS - they don't work properly anymore as updateProduct is not triggered.
I can reproduce it with latest FireFox & Chrome.

**Comment by matks** [comment]
> It's classic theme in an upgraded installation. To reproduce it is crucial to clear presta and browser cache to really work with new core.js.
> I have my own developed modules installed but they only insert JS - they don't work properly anymore as updateProduct is not triggered.
> I can reproduce it with latest FireFox & Chrome.

Thank you so much !

We are sure there an issue indeed however we have trouble finding out _exactly what_ and exactly _the complete scope of the consequences_.

Right now almost ten people are working on this issue 😛 you have the whole team working on this 😁 

It would be awesome to have the possibility to discuss further with you on this topic to fully understand it but GitHub is not really adapted to that kind of discussions, would it be possible to invite you on our Slack channel https://join.slack.com/t/prestashop/shared_invite/zt-dkmbz5qf-I~FlEWwmRUOXunc5ui0Ucg ?

**Comment by matks** [comment]
Fixed by https://github.com/PrestaShop/PrestaShop/pull/20052

**Comment by matks** [comment]
To provide some context about this issue ; we have identified that

1. the event `updateProduct` is fired
2. some JS code, including part (100% ? not sure) JS code from the Core works
3. some JS crashes (hence the console error)
4. the JS code listening that is called AFTER the crash on the event does NOT receive the event

**Comment by matks** [comment]
I have updated the title of this issue to "JS crash on FO product page in 1.7.6.6, preventing updateProduct event to be received"
